USE db_gamestore

CREATE TABLE tbl_UsuarioConta(
Tag SMALLINT PRIMARY KEY IDENTITY(100, 1), 
Email VARCHAR(50) NOT NULL UNIQUE,
Nome VARCHAR(50) NOT NULL,
Nick VARCHAR(50) NOT NULL,
Endereco VARCHAR(100),
Saldo DECIMAL DEFAULT 0
)

CREATE TABLE tbl_Amizade(
Amigo_A SMALLINT,
Amigo_B SMALLINT
CONSTRAINT pk_AB PRIMARY KEY (Amigo_A, amigo_B),
CONSTRAINT fk_Amigo_A FOREIGN KEY (Amigo_A)
REFERENCES tbl_UsuarioConta,
CONSTRAINT fk_Amigo_B FOREIGN KEY (Amigo_B)
REFERENCES tbl_UsuarioConta
CHECK NOT (Amigo_A = Amigo_B)
)

CREATE TABLE tbl_Distribuidora(
CNPJ VARCHAR(18) PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
Endereco VARCHAR(100)
)

CREATE TABLE tbl_Jogos(
Cod SMALLINT,
CNPJ VARCHAR(18) FOREIGN KEY(CNPJ)
REFERENCES tbl_Distribuidora(CNPJ),
Titulo VARCHAR(50) NOT NULL,
Avalia DECIMAL,
Lanca DATE,
Preco DECIMAL NOT NULL,
CONSTRAINT PK_JOGO PRIMARY KEY(CNPJ, Cod)
)

CREATE TABLE tbl_Genero(
Cod SMALLINT,
CNPJ VARCHAR(18),
Genero VARCHAR(50),
CONSTRAINT FK_Jogo FOREIGN KEY(CNPJ, Cod)
REFERENCES tbl_Jogo(CNPJ, Cod)
CONSTRAINT PK_Jogo_Genero PRIMARY KEY(CNPJ, Cod, Genero)
)

CREATE TABLE tbl_Promocao(
Cod_Prom SMALLINT PRIMARY KEY,
Desconto_Prom DECIMAL NOT NULL DEFAULT 0
CHECK(Desconto_Prom between 0 and 1) 
)

CREATE TABLE tbl_Compra(
Tag SMALLINT FOREIGN KEY REFERENCES tbl_UsuarioConta(Tag),
Cod SMALLINT,
CNPJ VARCHAR(18),
CONSTRAINT FK_Jogo_Compra FOREIGN KEY(CNPJ, Cod) REFERENCES tbl_Jogos(CNPJ, Cod)
Cod_Prom SMALLINT FOREIGN KEY REFERENCES tbl_Promocao,
CONSTRAINT PK_COMPRA PRIMARY KEY(CNPJ, Cod, Tag, Cod_Prom)
)